import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from "../components/NavBar/navbar";
import Left from "../components/Left/left";
import Right from "../components/Right/right";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


        <NavBar/>

        <div className={styles.leftAndRight}>
            <Left/>
            <Right/>
        </div>

    </div>
  )
}
